# Generated by Django 3.1.5 on 2021-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
