# Generated by Django 3.1.5 on 2021-01-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_text_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text_fr',
        ),
    ]
